### ISSUE TITLE
Cannot see Rain Sensor Entity

### ISSUE THREAD

**Issue by freemchr** [petergridge/openweathermaphistory#31]
Hi Peter

I tried to setup as an addon to the irrigation controller, and after setting up with the API and following instructions to add the API and also add the code for the rainfall monitoring, I cannot now add the sensor to Rain Sensor Entity in the irrigation settings under Zone configuration.

For some reason it is not listed as a binary.sensor 

Any help is appreciated.

**Comment by petergridge** [comment]
Hi,

This sensor provides the watering adjustment value, rather than a binary rain sensor. The amount of water applied varies depending on previous or forecast rain.

![image](https://github.com/petergridge/openweathermaphistory/assets/40281772/a2fc8a19-a534-415c-8f0b-11e359acaee0)

if you want this to behave like a binary sensor you can change the script to return a 0 (off), 1 (on) value.

Cheers
Pete

**Comment by freemchr** [comment]
Thank you really appreciated!
